// VSA Char — a whole word compressed into one hypervector, then predicted.
//
// Port of `demos/VSA_Char_Single.cpp` from jacobeverist/OgmaNeoDemos @ aogmaneo.
// See `doc/Demos.md` for the deviations from upstream.
//
// Each character is bound to a positional vector and the results bundled, so an
// entire word collapses into a single `SegVec<256, 8>`. Written out that vector *is*
// a CSDR — 256 columns of 8 cells — so it feeds a `Hierarchy` directly with no
// encoding step at all. The hierarchy learns to predict the next word's vector, and
// reading the answer means unbinding each position and cleaning up against the
// alphabet.
//
// That is the interesting part: the hierarchy never sees characters, only a
// distributed code, and the *decoding* is algebra rather than a learned decoder.
//
// Upstream's `resources/ts_snippet.txt` is missing from the repository, so the
// corpus is generated by default. `--text <path>` reads any ASCII file.
//
//   cargo run --release --example vsa_char
//   cargo run --release --example vsa_char -- --vocab 20 --successors 1

#[path = "support/mod.rs"]
mod support;

use dcc_sph::helpers::Int3;
use dcc_sph::hierarchy::{Hierarchy, IoDesc, IoType, LayerDesc};

use support::args::Args;
use support::checkpoint;
use support::env::text::{Corpus, ALPHABET};
use support::metrics::{Recorder, Summary};
use support::report::Rolling;
use support::rng::seed_everything;
use support::sweep;
use support::vec::{cleanup, Bundle, SegVec};

/// Upstream's `S` and `L`. 256 segments of 8 lays out as a 16x16 grid of columns.
const S: usize = 256;
const L: usize = 8;
type V = SegVec<S, L>;

fn main() {
    let args = Args::parse();

    let mut rec = Recorder::from_args("vsa_char", &args);
    sweep::drive(&args, &mut rec, run);
    rec.finish();
}

fn run(args: &Args, seed: u64, rec: &mut Recorder) -> Summary {
    let train_steps: usize = args.get("train-steps", 40_000);
    let test_steps: usize = args.get("test-steps", 4_000);
    let every: usize = args.get("every", 10_000);
    let silent = args.flag("silent");
    let quiet = silent || args.flag("quiet");

    macro_rules! say {
        ($($arg:tt)*) => {
            if !silent {
                println!($($arg)*);
            }
        };
    }

    let mut rng = seed_everything(seed);

    let corpus = Corpus::from_args(args, &mut rng);
    let max_len = corpus.max_word_len();

    rec.config("train_steps", train_steps);
    rec.config("test_steps", test_steps);
    rec.config("vocab", corpus.vocab());
    rec.config("max_word_len", max_len);

    // --- Codebooks ---
    //
    // One random vector per character, one per position. Both are fixed: the
    // algebra does the work, and nothing about them is learned.

    let alphabet: Vec<V> = (0..ALPHABET).map(|_| V::randomized(&mut rng)).collect();
    let positions: Vec<V> = (0..max_len.max(1)).map(|_| V::randomized(&mut rng)).collect();

    // Every word's vector, precomputed.
    let word_vecs: Vec<V> = corpus
        .words
        .iter()
        .map(|w| encode_word(w, &alphabet, &positions))
        .collect();

    // --- Hierarchy ---
    //
    // Upstream: IO (16, 16, 8) — 16*16 = S columns, z = L — with up_radius 5 and
    // down_radius 3, over two layers of 7x7x64.

    let io_descs = vec![IoDesc {
        size: Int3::new(16, 16, L as i32),
        io_type: IoType::Prediction,
        num_dendrites_per_cell: 4,
        up_radius: 5,
        down_radius: 3,
        ..Default::default()
    }];

    let layer_descs: Vec<LayerDesc> = (0..2)
        .map(|_| LayerDesc {
            hidden_size: Int3::new(7, 7, 64),
            num_dendrites_per_cell: 4,
            up_radius: 2,
            recurrent_radius: 0,
            down_radius: 2,
            ticks_per_update: 1,
            top_feedback: false,
        })
        .collect();

    let mut h = Hierarchy::new();
    h.init_random(&io_descs, &layer_descs);
    checkpoint::maybe_load(&mut h, args);

    say!("VSA Char — {} words, sequence of {}, seed {seed}", corpus.vocab(), corpus.sequence.len());
    say!("  SegVec<{S}, {L}> per word: each character bound to a position, then bundled");
    say!("  IO (16,16,{L}) Prediction — the vector *is* the CSDR, so there is no encoder");
    say!("  2 layers 7x7x64, {train_steps} train + {test_steps} test steps");
    say!();

    // A round-trip check before training: if the encoding itself cannot be read
    // back, nothing downstream means anything.
    let encode_acc = encoding_fidelity(&corpus, &word_vecs, &alphabet, &positions);
    say!("  encoding round trip: {:.1}% of characters recover from the word vector", encode_acc * 100.0);
    say!();

    // --- Train ---

    let mut train_hits = Rolling::new(4_000, 0.001);

    for t in 0..train_steps {
        let i = t % corpus.sequence.len();
        let word = corpus.sequence[i];
        let next = corpus.sequence[(i + 1) % corpus.sequence.len()];

        // Score the standing prediction before stepping: it is about this step.
        let predicted = V::from_cis(h.get_prediction_cis(0));
        if let Some((best, _)) = cleanup(&predicted, &word_vecs) {
            train_hits.push(if best == word { 1.0 } else { 0.0 });
        }
        let _ = next;

        let cis = word_vecs[word].to_cis();
        h.step(&[&cis], true, 0.0, 0.0);

        if every > 0 && (t + 1) % every == 0 {
            rec.sample(t as u64 + 1, &[("train_accuracy", train_hits.mean() as f64)]);
            if !quiet {
                say!(
                    "  step {:>8} / {train_steps} | online word accuracy {:.1}%",
                    t + 1,
                    train_hits.mean() * 100.0
                );
            }
        }
    }

    // --- Test: learning off ---

    let mut word_hits = Rolling::new(100_000, 0.001);
    let mut char_hits = Rolling::new(100_000, 0.001);
    let mut sim = Rolling::new(100_000, 0.001);

    let offset = train_steps % corpus.sequence.len();

    for t in 0..test_steps {
        let i = (offset + t) % corpus.sequence.len();
        let word = corpus.sequence[i];
        let next = corpus.sequence[(i + 1) % corpus.sequence.len()];

        let cis = word_vecs[word].to_cis();
        h.step(&[&cis], false, 0.0, 0.0);

        let predicted = V::from_cis(h.get_prediction_cis(0));

        // Whole-word recall: nearest word vector to the prediction.
        if let Some((best, s)) = cleanup(&predicted, &word_vecs) {
            word_hits.push(if best == next { 1.0 } else { 0.0 });
            sim.push(s);
        }

        // Character-level recall: unbind each position and clean up against the
        // alphabet, which is what the algebra is for.
        let target = &corpus.words[next];
        let decoded = decode_word(&predicted, &alphabet, &positions, target.len());
        for (a, b) in decoded.chars().zip(target.chars()) {
            char_hits.push(if a == b { 1.0 } else { 0.0 });
        }
    }

    // --- Report ---

    // The best accuracy anything could reach on this sequence, measured from the
    // corpus itself. Judging against chance alone would call a model that has hit
    // the ceiling on a two-successor chain "a mediocre 50%".
    let ceiling = corpus.predictability();

    say!();
    say!("Held-out prediction over {test_steps} steps:");
    say!(
        "  next-word accuracy   {:.1}%  (chance {:.1}%, ceiling {:.1}%)",
        word_hits.mean() * 100.0,
        corpus.chance() * 100.0,
        ceiling * 100.0
    );
    say!("  character accuracy   {:.1}%", char_hits.mean() * 100.0);
    say!("  mean similarity to the correct word vector  {:.3}", sim.mean());

    if !quiet {
        say!("\n  A few predictions (predicted -> actual):");
        let mut shown = 0;
        for t in 0..corpus.sequence.len().min(64) {
            let i = (offset + t) % corpus.sequence.len();
            let word = corpus.sequence[i];
            let next = corpus.sequence[(i + 1) % corpus.sequence.len()];
            let cis = word_vecs[word].to_cis();
            h.step(&[&cis], false, 0.0, 0.0);
            let predicted = V::from_cis(h.get_prediction_cis(0));
            let decoded = decode_word(&predicted, &alphabet, &positions, corpus.words[next].len());
            let mark = if decoded == corpus.words[next] { "  " } else { " x" };
            say!("   {} {:>8} -> {:<8}{mark}", corpus.words[word], decoded, corpus.words[next]);
            shown += 1;
            if shown >= 8 {
                break;
            }
        }
    }

    let mut summary = Summary::new();
    summary.push("word_accuracy", word_hits.mean() as f64);
    summary.push("char_accuracy", char_hits.mean() as f64);
    summary.push("chance", corpus.chance());
    summary.push("ceiling", ceiling);
    summary.push("fraction_of_ceiling", word_hits.mean() as f64 / ceiling.max(1e-9));
    summary.push("similarity", sim.mean() as f64);
    summary.push("encoding_fidelity", encode_acc as f64);
    summary.push("vocab", corpus.vocab() as f64);

    let of_ceiling = word_hits.mean() as f64 / ceiling.max(1e-9);

    say!();
    if of_ceiling > 0.9 {
        say!(
            "At the ceiling: {:.1}% of the {:.1}% this sequence allows, decoded purely by",
            of_ceiling * 100.0,
            ceiling * 100.0
        );
        say!("unbinding each position and cleaning up against the alphabet.");
        summary.verdict(true, "reached the sequence's predictability ceiling");
    } else if (word_hits.mean() as f64) > corpus.chance() * 2.0 {
        say!(
            "Learning: {:.1}% against {:.1}% chance, but only {:.0}% of the {:.1}% ceiling —",
            word_hits.mean() * 100.0,
            corpus.chance() * 100.0,
            of_ceiling * 100.0,
            ceiling * 100.0
        );
        say!("try more --train-steps.");
        summary.verdict(true, "above chance but short of the ceiling");
    } else {
        say!("Not converged: next-word accuracy is near chance — try more --train-steps,");
        say!("or --successors 1 to make the sequence deterministic.");
        summary.verdict(false, "next-word accuracy near chance");
    }

    checkpoint::maybe_save(&h, args);

    rec.finish_summary(&summary);
    summary
}

/// Bundle each character bound to its positional vector, then thin.
fn encode_word(word: &str, alphabet: &[V], positions: &[V]) -> V {
    let mut b = Bundle::<S, L>::zero();
    for (i, c) in word.chars().enumerate() {
        let code = (c as usize) % ALPHABET;
        let pos = i.min(positions.len() - 1);
        b.add_vec(&alphabet[code].bind(&positions[pos]), 1.0);
    }
    b.thin()
}

/// Unbind each position and clean up against the alphabet.
fn decode_word(v: &V, alphabet: &[V], positions: &[V], len: usize) -> String {
    (0..len)
        .map(|i| {
            let pos = i.min(positions.len() - 1);
            let recovered = v.unbind(&positions[pos]);
            match cleanup(&recovered, alphabet) {
                Some((idx, _)) => idx as u8 as char,
                None => '?',
            }
        })
        .collect()
}

/// How much of a word survives the encode/decode round trip, before any learning.
///
/// This is the ceiling on character accuracy: bundling `k` pairs into one vector is
/// lossy, and if the words are long enough relative to `S` and `L` the encoding
/// alone loses them. Reporting it separates "the hierarchy did not learn" from
/// "the representation could not hold the word in the first place".
fn encoding_fidelity(corpus: &Corpus, word_vecs: &[V], alphabet: &[V], positions: &[V]) -> f32 {
    let mut hits = 0usize;
    let mut total = 0usize;
    for (w, v) in corpus.words.iter().zip(word_vecs) {
        let decoded = decode_word(v, alphabet, positions, w.len());
        for (a, b) in decoded.chars().zip(w.chars()) {
            if a == b {
                hits += 1;
            }
            total += 1;
        }
    }
    if total == 0 {
        0.0
    } else {
        hits as f32 / total as f32
    }
}
